const data = [
  {
    is_assured: true,
    id: 1001,
    discount: 60,
    original_cost: 1399,
    image:
      "https://rukminim1.flixcart.com/image/309/371/khkvukw0-0/t-shirt/q/w/c/m-20a3089j5000i-tt3-united-colors-of-benetton-original-imafxk6pkhfpseqk.jpeg?q=50",
    name: "Solid Men Polo Neck Orange T-Shirt",
    made_by: "United Colors of Benetton",
    is_for: "Men",
    catogeries: "Clothing And Accessories",
    size: ["S", "M", "L"],
    minor_details: null,
    extra_offers: null,
  },
  {
    is_assured: true,
    id: 1002,
    discount: 76,
    original_cost: 999,
    image:
      "https://rukminim1.flixcart.com/image/367/440/kf1fo280hlty2aw-0/t-shirt/w/s/e/-original-imafdfvvr8hqdu65.jpeg?q=50",
    name: "Striped Men Hooded Neck Red, Black T-Shirt",
    made_by: "HELMONT",
    is_for: "Men",
    catogeries: "Clothing And Accessories",
    size: ["S", "M", "L"],
    minor_details: null,
    extra_offers: null,
  },
  {
    is_assured: false,
    id: 1003,
    discount: 80,
    original_cost: 1999,
    image:
      "https://rukminim1.flixcart.com/image/459/551/k1nw9zk0/lehenga-choli/m/9/f/free-trilok-pink-lehenga-01-ashtavinayak-original-imafhe5dezzvhua3.jpeg?q=50",
    name: "Satin Embroidered, Embellished Gown/Anarkali Kurta & Bottom Material  (Semi Stitched)",
    made_by: "Sixteen Creation",
    is_for: "Women",
    catogeries: "Clothing And Accessories",
    size: [],
    minor_details: null,
    extra_offers: null,
  },
  {
    is_assured: false,
    id: 1004,
    discount: 80,
    original_cost: 1999,
    image:
      "https://rukminim1.flixcart.com/image/459/551/k1nw9zk0/lehenga-choli/m/9/f/free-trilok-pink-lehenga-01-ashtavinayak-original-imafhe5dezzvhua3.jpeg?q=50",
    name: "Satin Embroidered, Embellished Gown/Anarkali Kurta & Bottom Material  (Semi Stitched)",
    made_by: "Sixteen Creation",
    is_for: ["Women"],
    catogeries: "Clothing And Accessories",
    size: [],
    minor_details: "Semi Stitched",
    extra_offers: null,
  },
  {
    is_assured: false,
    id: 1005,
    discount: 71,
    original_cost: 1599,
    image:
      "https://rukminim1.flixcart.com/image/459/551/knxiavk0/kids-ethnic-set/5/g/u/4-5-years-blue-kurta-set-bold-born-original-imag2gegdz8yxj6f.jpeg?q=50",
    name: "Boys Festive & Party Shirt, Waistcoat and Pant Set  (Blue Pack of 1) Special price",
    made_by: "Bold Born",
    is_for: "Kids",
    catogeries: "Clothing And Accessories",
    size: ["S", "L"],
    minor_details: "Blue Pack of 1",
    extra_offers: null,
  },
  {
    is_assured: true,
    id: 1006,
    discount: 66,
    original_cost: 899,
    image:
      "https://rukminim1.flixcart.com/image/459/551/juljwcw0/kids-ethnic-set/d/x/p/2-3-years-modi-rjacket-33-6-12-month-new-gen-original-imaffzrdgqhe2hge.jpeg?q=50",
    name: "Boys Festive & Party Ethnic Jacket, Kurta and Legging Set  (Red Pack of 2)",
    made_by: "New gen",
    is_for: "Kids",
    catogeries: "Clothing And Accessories",
    size: ["S", "2-3 years"],
    minor_details: "Red Pack of 2",
    extra_offers: null,
  },
];

export default data;
